# Generated by Django 2.1.15 on 2024-04-17 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peer_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.TextField(blank=True, default='[unspecified]', null=True)),
                ('grading_period', models.TextField(blank=True, default='[unspecified]', null=True)),
                ('grade', models.FloatField(default=0)),
                ('max_grade', models.FloatField(default=0)),
                ('grading_method', models.TextField(blank=True, default='[ungraded]', null=True)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('gradee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradee', to='peer_course.CourseMember')),
            ],
        ),
    ]
